const imageMapper = {
    "../assets/Carregador/carregadorIos.jpg": require("../assets/Carregador/carregadorIos.jpg"),
    "../assets/Carregador/caboIosKaidi.jpeg": require("../assets/Carregador/caboIosKaidi.jpeg"),
    "../assets/Carregador/caboIosPrimeira.jpeg": require("../assets/Carregador/caboIosPrimeira.jpeg"),
    "../assets/Carregador/caboLehmoxTipoC.jpeg": require("../assets/Carregador/caboLehmoxTipoC.jpeg"),
    "../assets/Carregador/caboTipoCHRebos.jpeg": require("../assets/Carregador/caboTipoCHRebos.jpeg"),
    "../assets/Carregador/carregadorInducao.jpeg": require("../assets/Carregador/carregadorInducao.jpeg"),
    "../assets/Carregador/carregadorIOSHmaston.jpeg": require("../assets/Carregador/carregadorIOSHmaston.jpeg"),
    "../assets/Carregador/carregadorTurboIOSHMaston.jpeg": require("../assets/Carregador/carregadorTurboIOSHMaston.jpeg"),
    "../assets/Carregador/carregadorTurboIOSLehmox.jpeg": require("../assets/Carregador/carregadorTurboIOSLehmox.jpeg"),
    "../assets/Carregador/carregadorTurboTC.jpeg": require("../assets/Carregador/carregadorTurboTC.jpeg"),
    "../assets/Carregador/carregadorTurboV8.jpeg": require("../assets/Carregador/carregadorTurboV8.jpeg"),
    "../assets/Carregador/carregadorVeicular.jpeg": require("../assets/Carregador/carregadorVeicular.jpeg"),
    "../assets/Carregador/fonteTurboLehmox.jpeg": require("../assets/Carregador/fonteTurboLehmox.jpeg"),
    "../assets/Carregador/powerBank5000.jpeg": require("../assets/Carregador/powerBank5000.jpeg"),
    "../assets/Fones/foneAirDots.jpg": require("../assets/Fones/foneAirDots.jpg"),
    "../assets/Fones/foneHrebosIos.jpg": require("../assets/Fones/foneHrebosIos.jpg"),
    "../assets/Fones/foneInovaBT.jpeg": require("../assets/Fones/foneInovaBT.jpeg"),
    "../assets/Fones/foneIntraHmaston.jpeg": require("../assets/Fones/foneIntraHmaston.jpeg"),
    "../assets/Fones/foneIntraPmCell.jpeg": require("../assets/Fones/foneIntraPmCell.jpeg"),
    "../assets/Fones/foneJblBT.jpeg": require("../assets/Fones/foneJblBT.jpeg"),
    "../assets/Fones/foneLehmox.jpg": require("../assets/Fones/foneLehmox.jpg"),
    "../assets/Fones/foneLehmoxTipoS.jpeg": require("../assets/Fones/foneLehmoxTipoS.jpeg"),
    "../assets/Fones/fonePMTipoIOS.jpeg": require("../assets/Fones/fonePMTipoIOS.jpeg"),
    "../assets/Caixas/caixaJBLExtreme.jpeg": require("../assets/Caixas/caixaJBLExtreme.jpeg"),
    "../assets/Caixas/caixaLehmox.jpg": require("../assets/Caixas/caixaLehmox.jpg"),
    "../assets/Caixas/caixaInova.jpg": require("../assets/Caixas/caixaInova.jpg"),
    "../assets/Caixas/caixaMinifun.jpg": require("../assets/Caixas/caixaMinifun.jpg"),
    "../assets/Caixas/lampadaCaixa.jpeg": require("../assets/Caixas/lampadaCaixa.jpeg"),
    "../assets/Utilitaries/balanca.jpeg": require("../assets/Utilitaries/balanca.jpeg"),
    "../assets/Utilitaries/globo.jpeg": require("../assets/Utilitaries/globo.jpeg"),
    "../assets/Utilitaries/hubUsb.jpeg": require("../assets/Utilitaries/hubUsb.jpeg"),
    "../assets/Utilitaries/protetorCabo.jpeg": require("../assets/Utilitaries/protetorCabo.jpeg"),
    "../assets/Utilitaries/ringLight.jpeg": require("../assets/Utilitaries/ringLight.jpeg"),
    "../assets/smartWatch/smartWatch.jpg": require("../assets/smartWatch/smartWatch.jpg"),
    "../assets/suportesVeiculares/suporteCarro.jpeg": require("../assets/suportesVeiculares/suporteCarro.jpeg"),
    "../assets/peliculas/pelicula3D.jpg": require("../assets/peliculas/pelicula3D.jpg"),
    "../assets/peliculas/peliculaTraseira.jpg": require("../assets/peliculas/peliculaTraseira.jpg"),
    "../assets/peliculas/peliculaCeramica.jpg": require("../assets/peliculas/peliculaCeramica.jpg"),
    "../assets/peliculas/peliculaVidro.jpg": require("../assets/peliculas/peliculaVidro.jpg"),
    };
    
    export default imageMapper;
  