const imageMapper = {
    "../assets/Carregador/carregadorIos.jpeg": require("../assets/Carregador/carregadorIos.jpeg"),
    "../assets/Carregador/caboIosKaidi.jpeg": require("../assets/Carregador/caboIosKaidi.jpeg"),
    "../assets/Carregador/caboIosPrimeira.jpeg": require("../assets/Carregador/caboIosPrimeira.jpeg"),
    "../assets/Carregador/caboLehmoxTipoC.jpeg": require("../assets/Carregador/caboLehmoxTipoC.jpeg"),
    "../assets/Carregador/caboTipoCHRebos.jpeg": require("../assets/Carregador/caboTipoCHRebos.jpeg"),
    "../assets/Carregador/carregadorInducao.jpeg": require("../assets/Carregador/carregadorInducao.jpeg"),
    "../assets/Carregador/carregadorIOSHmaston.jpeg": require("../assets/Carregador/carregadorIOSHmaston.jpeg"),
    "../assets/Carregador/carregadorTurboIOSHMaston.jpeg": require("../assets/Carregador/carregadorTurboIOSHMaston.jpeg"),
    "../assets/Carregador/carregadorTurboIOSLehmox.jpeg": require("../assets/Carregador/carregadorTurboIOSLehmox.jpeg"),
    "../assets/Carregador/carregadorTurboTC.jpeg": require("../assets/Carregador/carregadorTurboTC.jpeg"),
    "../assets/Carregador/carregadorTurboV8.jpeg": require("../assets/Carregador/carregadorTurboV8.jpeg"),
    "../assets/Carregador/carregadorVeicular.jpeg": require("../assets/Carregador/carregadorVeicular.jpeg"),
    "../assets/Carregador/fonteTurboLehmox.jpeg": require("../assets/Carregador/fonteTurboLehmox.jpeg"),
    "../assets/Carregador/powerBank5000.jpeg": require("../assets/Carregador/powerBank5000.jpeg"),
    "../assets/Fones/foneAirDots.jpeg": require("../assets/Fones/foneAirDots.jpeg"),
    "../assets/Fones/foneHrebosIos.jpeg": require("../assets/Fones/foneHrebosIos.jpeg"),
    "../assets/Fones/foneInovaBT.jpeg": require("../assets/Fones/foneInovaBT.jpeg"),
    "../assets/Fones/foneIntraHmaston.jpeg": require("../assets/Fones/foneIntraHmaston.jpeg"),
    "../assets/Fones/foneIntraPmCell.jpeg": require("../assets/Fones/foneIntraPmCell.jpeg"),
    "../assets/Fones/foneJblBT.jpeg": require("../assets/Fones/foneJblBT.jpeg"),
    "../assets/Fones/foneLehmox.jpeg": require("../assets/Fones/foneLehmox.jpeg"),
    "../assets/Fones/foneLehmoxTipoS.jpeg": require("../assets/Fones/foneLehmoxTipoS.jpeg"),
    "../assets/Fones/fonePMTipoIOS.jpeg": require("../assets/Fones/fonePMTipoIOS.jpeg"),
    "../assets/Caixas/caixaJBLExtreme.jpeg": require("../assets/Caixas/caixaJBLExtreme.jpeg"),
    "../assets/Caixas/caixaLehmox.jpeg": require("../assets/Caixas/caixaLehmox.jpeg"),
    "../assets/Caixas/caixaInova.jpeg": require("../assets/Caixas/caixaInova.jpeg"),
    "../assets/Caixas/caixaMinifun.jpeg": require("../assets/Caixas/caixaMinifun.jpeg"),
    "../assets/Caixas/lampadaCaixa.jpeg": require("../assets/Caixas/lampadaCaixa.jpeg"),
    "../assets/Utilitaries/balanca.jpeg": require("../assets/Utilitaries/balanca.jpeg"),
    "../assets/Utilitaries/globo.jpeg": require("../assets/Utilitaries/globo.jpeg"),
    "../assets/Utilitaries/hubUsb.jpeg": require("../assets/Utilitaries/hubUsb.jpeg"),
    "../assets/Utilitaries/protetorCabo.jpeg": require("../assets/Utilitaries/protetorCabo.jpeg"),
    "../assets/Utilitaries/ringLight.jpeg": require("../assets/Utilitaries/ringLight.jpeg"),
    "../assets/smartWatch/smartWatch.jpeg": require("../assets/smartWatch/smartWatch.jpeg"),
    "../assets/suportesVeiculares/suporteCarro.jpeg": require("../assets/suportesVeiculares/suporteCarro.jpeg"),
    "../assets/peliculas/pelicula3D.jpeg": require("../assets/peliculas/pelicula3D.jpeg"),
    "../assets/peliculas/peliculaTraseira.jpeg": require("../assets/peliculas/peliculaTraseira.jpeg"),
    "../assets/peliculas/peliculaCeramica.jpeg": require("../assets/peliculas/peliculaCeramica.jpeg"),
    "../assets/peliculas/peliculaVidro.jpeg": require("../assets/peliculas/peliculaVidro.jpeg"),
    };
    
    export default imageMapper;
  